// Delibird Mart — Kalos Z-A Regional Pokémon Item Catalog

export const PRODUCTS = [
  {
    id: 'p01',
    name: "Mega Ring",
    subtitle: "Mega Evolution Amplifier",
    category: 'Accessories',
    region: 'Kalos Z-A',
    rarity: 'EX',
    type: 'psychic',
    typeLabel: 'Psychic',
    price: 380000,
    rating: 5.0,
    stock: 2,
    description: "Forged deep within the Pokémon League's inner vault by Diantha herself. Resonates with Mega Stones to amplify Bond Phenomenon transformations.",
    stats: { bondAmp: '+100%', range: 'All Species', energy: 'Infinite' },
    image: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=600&q=80',
    tags: ['Mega Evolution', 'Key Stone', 'Kalos Exclusive']
  },
  {
    id: 'p02',
    name: "Charizardite X",
    subtitle: "Mega Stone — Fire / Dragon",
    category: 'Mega Stones',
    region: 'Kalos Z-A',
    rarity: 'S-Rank',
    type: 'dragon',
    typeLabel: 'Dragon',
    price: 220000,
    rating: 4.9,
    stock: 5,
    description: "Imbued with the Blue Flame of Kalos. Transforms Charizard into a Mega Charizard X — a ferocious Dragon-type powerhouse with the Tough Claws ability.",
    stats: { atk: '+168 → 204', type: 'Fire→Dragon', ability: 'Tough Claws' },
    image: 'https://images.unsplash.com/photo-1609096458733-95b38583ac4e?auto=format&fit=crop&w=600&q=80',
    tags: ['Mega Stone', 'Charizard', 'Dragon Power']
  },
  {
    id: 'p03',
    name: "Delibird Ice Elixir",
    subtitle: "Pure Restoration Extract",
    category: 'Elixirs',
    region: 'Kalos Z-A',
    rarity: 'A-Rank',
    type: 'ice',
    typeLabel: 'Ice',
    price: 18000,
    rating: 4.8,
    stock: 40,
    description: "Brewed from crystalline ice essence harvested in the Icy Rock caves of Kalos. Fully restores HP and PP with a refreshing arctic burst.",
    stats: { hpRestore: '100%', ppRestore: 'All Moves', effect: 'Chill Aura' },
    image: 'https://images.unsplash.com/photo-1514733670139-4d87a1941d55?auto=format&fit=crop&w=600&q=80',
    tags: ['Elixir', 'Delibird Special', 'Full Restore']
  },
  {
    id: 'p04',
    name: "Gengarite",
    subtitle: "Mega Stone — Ghost",
    category: 'Mega Stones',
    region: 'Kalos Z-A',
    rarity: 'S-Rank',
    type: 'ghost',
    typeLabel: 'Ghost',
    price: 195000,
    rating: 4.9,
    stock: 7,
    description: "A sinister stone that awakens Gengar's shadow nature. Transforms it into Mega Gengar with the Shadow Tag ability — no opponent can escape.",
    stats: { spAtk: '+130 → 170', ability: 'Shadow Tag', weight: 'Levitates' },
    image: 'https://images.unsplash.com/photo-1566694271453-390536dd1f0d?auto=format&fit=crop&w=600&q=80',
    tags: ['Mega Stone', 'Gengar', 'Shadow Tag']
  },
  {
    id: 'p05',
    name: "Lumiose Trainer Badge Set",
    subtitle: "Official Kalos Gym Collection",
    category: 'Accessories',
    region: 'Kalos Z-A',
    rarity: 'A-Rank',
    type: 'normal',
    typeLabel: 'Normal',
    price: 85000,
    rating: 4.7,
    stock: 15,
    description: "Complete set of all 8 official Kalos Region Gym Badges, hand-enameled in Lumiose City. Display case included. Proof of a Champion-caliber trainer.",
    stats: { count: '8 Badges', material: '18K Gold Fill', display: 'Holographic Case' },
    image: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?auto=format&fit=crop&w=600&q=80',
    tags: ['Kalos Badges', 'Collector', 'Championship']
  },
  {
    id: 'p06',
    name: "Delibird Dimensional Pouch",
    subtitle: "Infinite-Capacity Carry Bag",
    category: 'Accessories',
    region: 'Kalos Z-A',
    rarity: 'S-Rank',
    type: 'ice',
    typeLabel: 'Ice',
    price: 130000,
    rating: 5.0,
    stock: 8,
    description: "Woven by Delibird couriers using Kalos-region space-folding thread. Stores up to 999 items in a pocket dimension with zero carry weight.",
    stats: { capacity: '999 Slots', weight: '0 kg', lock: 'Biometric Seal' },
    image: 'https://images.unsplash.com/photo-1549465220-1a8b9238cd48?auto=format&fit=crop&w=600&q=80',
    tags: ['Storage', 'Delibird Courier', 'Pocket Dimension']
  },
  {
    id: 'p07',
    name: "Ampharosite",
    subtitle: "Mega Stone — Electric / Dragon",
    category: 'Mega Stones',
    region: 'Kalos Z-A',
    rarity: 'S-Rank',
    type: 'electric',
    typeLabel: 'Electric',
    price: 180000,
    rating: 4.8,
    stock: 9,
    description: "Electrifies Ampharos with the power of a thousand thunderclaps. Mega Ampharos gains the Dragon typing and the Mold Breaker ability.",
    stats: { spAtk: '+115 → 165', type: 'Elec→Dragon', ability: 'Mold Breaker' },
    image: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=600&q=80',
    tags: ['Mega Stone', 'Ampharos', 'Electric Dragon']
  },
  {
    id: 'p08',
    name: "Z-A Mystery Crate",
    subtitle: "Kalos Legends Gacha Box",
    category: 'Mystery',
    region: 'Kalos Z-A',
    rarity: 'A-Rank',
    type: 'fairy',
    typeLabel: 'Fairy',
    price: 95000,
    rating: 4.9,
    stock: 20,
    description: "A sealed dimensional crate recovered from the Z-A Urban Redevelopment Project ruins. Guaranteed to contain at minimum one S-Rank Kalos artifact.",
    stats: { minRarity: 'S-Rank Item', source: 'Lumiose Ruins', odds: '100% S+' },
    image: 'https://images.unsplash.com/photo-1607462109225-6b64ae2dd3cb?auto=format&fit=crop&w=600&q=80',
    tags: ['Mystery Box', 'Legends Z-A', 'Gacha']
  }
];

export const CATEGORIES = ['All', 'Mega Stones', 'Elixirs', 'Accessories', 'Mystery'];
export const RARITIES   = ['All', 'EX', 'S-Rank', 'A-Rank'];
export const REGIONS    = ['Kalos Z-A', 'Kanto', 'Johto', 'Paldea'];

export const TYPE_COLORS = {
  fire: 'type-fire', water: 'type-water', electric: 'type-electric',
  ice: 'type-ice', dragon: 'type-dragon', dark: 'type-dark',
  psychic: 'type-psychic', ghost: 'type-ghost', steel: 'type-steel',
  fairy: 'type-fairy', normal: 'type-normal',
};
